server:
  ip: localhost
  port: 9090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/graduation?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: "000312"
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

mybatis:
  mapper-locations: classpath:mapper/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

files:
  upload:
    path: C:/Users/Kyrie/Desktop/毕设/files/
    avatarpath: C:/Users/Kyrie/Desktop/毕设/avatars/
#    path: /home/files/
#    avatarpath: /home/avatars/